export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";
export const CART_SAVE_PAYMENT = "CART_SAVE_PAYMENT"
export const CART_SAVE_SUCCESS = "CART_SAVE_PURCHASE"
export const CART_SAVE_REQUEST = "CART_SAVE_REQUEST"
export const PURCHASE_SAVE_REQUEST = "PURCHASE_SAVE_REQUEST"
export const PURCHASE_SAVE_SUCCESS = "PURCHASE_SAVE_SUCCESS"